name: "HCL AppScan Static Analyzer"
on:
  pull_request:
    types: [opened,synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run AppScan Static Analyzer
        uses: ./
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: e35ea96d-cae0-499a-a3ed-7a4efd77b269
          wait_for_analysis: true
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
